### ISSUE TITLE
More button

### ISSUE THREAD

**Issue by kaushikom** [hmjatt/Calculator#2]
When I hover over the more button, it turns black, as does the dropdown menu that appears. However, as I move my pointer outside of the calculator body, both the more button and the dropdown menu turn white. Is this a bug or a feature?

**Comment by hmjatt** [comment]
Hey @OmKaushik71, thanks for raising this issue. It was originally an feature but I see what you are saying, it adds little bit of inconsistency to the UI.
If you want to change that I would be more than happy to accept your Pull Request with the modification you would like to see in the app.
Let me know what you think and thanks again 😃  - @hmjatt
